apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-account

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  DB_PASSWORD: "bXktc2VjcmV0LXB3Cg==" # Base64 encoded "my-secret-pw"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  DB_HOST: "db"

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth-service-account
      containers:
        - name: auth-container
          image: devopseasylearning/banga-auth:v0.0.1
          ports:
          - containerPort: 8080
          envFrom:
            - secretRef:
                name: auth-secret
          envFrom:
            - configMapRef:
                name: auth-configmap
    
