apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-service-account

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "bXktc2VjcmV0LXB3Cg=="   # Base64 encoded value of "my-secret-pw"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   # Adjust the size as needed

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: "db-service"
  replicas: 1   # Adjust as needed
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      serviceAccountName: db-service-account
      containers:
      - name: db
        image: devopseasylearning/banga-db:v0.0.1
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_ROOT_PASSWORD
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql/data-aj
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306   # Adjust the port as needed
      targetPort: 3306
