version: '3'

services:
  ui:
    image: devopseasylearning/banga-ui:v0.0.1
    container_name: ui_service
    hostname: aj_server_ui
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=8080
      - WEATHER_HOST=weather
      - WEATHER_PORT=5000
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - auth
    restart: always
    networks:
      - aj-network

  auth:
    image: devopseasylearning/banga-auth:v0.0.1
    container_name: auth_service
    hostname: aj_server_auth
    expose:
      - 8080
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my-secret-pw
    depends_on:
      - db
    restart: always
    networks:
      - aj-network

  weather:
    image: devopseasylearning/banga-weather:v0.0.1
    container_name: weather_service
    hostname: aj_server_weather
    expose:
      - 5000
    environment:
      - APIKEY=ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - aj-network

  db:
    image: devopseasylearning/banga-db:v0.0.1
    container_name: db_service
    hostname: aj_server_db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - banga-db-data:/var/lib/mysql/data
    restart: always
    networks:
      - aj-network

  redis:
    image: redis:latest
    container_name: redis_service
    hostname: aj_server_redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data1:/data
    restart: always
    networks:
      - aj-network

volumes:
  banga-db-data:
  redis-data1:

networks:
  aj-network:
    driver: bridge
