apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-service-account

---

apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
type: Opaque
data:
  APIKEY: "ZWNiYzM5NmY0Nm1zaGI2NWNiYjFmODJjZjMzNHBhZjZjYzg3anNuYTFlOTYyYTNjNTQyCg=="   # Base64 encoded value of "ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      serviceAccountName: weather-service-account
      containers:
      - name: weather
        image: devopseasylearning/banga-weather:v0.0.1
        env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: APIKEY
        ports:
        - containerPort: 5000
     

---

apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 5000   # Adjust the port as needed
      targetPort: 5000
